// Canonical TOC observation and diagnosis model.
//
// Maps to Go types in codeberg.org/binaryphile/toc/core.
// Cross-language consumers (Java/Pepin, Perl/Ventus) use this schema
// for NATS transport and sidecar adapters.
//
// Presence model: fields whose observability varies use proto3
// optional. Absent means "not observed this window." Present with
// value zero means "observed zero."

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: toc/v1/toc.proto

package tocpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StageState classifies a stage's operational state.
type StageState int32

const (
	StageState_STAGE_STATE_UNSPECIFIED StageState = 0
	StageState_STAGE_STATE_HEALTHY     StageState = 1
	StageState_STAGE_STATE_STARVED     StageState = 2
	StageState_STAGE_STATE_BLOCKED     StageState = 3
	StageState_STAGE_STATE_SATURATED   StageState = 4
	StageState_STAGE_STATE_BROKEN      StageState = 5
)

// Enum value maps for StageState.
var (
	StageState_name = map[int32]string{
		0: "STAGE_STATE_UNSPECIFIED",
		1: "STAGE_STATE_HEALTHY",
		2: "STAGE_STATE_STARVED",
		3: "STAGE_STATE_BLOCKED",
		4: "STAGE_STATE_SATURATED",
		5: "STAGE_STATE_BROKEN",
	}
	StageState_value = map[string]int32{
		"STAGE_STATE_UNSPECIFIED": 0,
		"STAGE_STATE_HEALTHY":     1,
		"STAGE_STATE_STARVED":     2,
		"STAGE_STATE_BLOCKED":     3,
		"STAGE_STATE_SATURATED":   4,
		"STAGE_STATE_BROKEN":      5,
	}
)

func (x StageState) Enum() *StageState {
	p := new(StageState)
	*p = x
	return p
}

func (x StageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageState) Descriptor() protoreflect.EnumDescriptor {
	return file_toc_v1_toc_proto_enumTypes[0].Descriptor()
}

func (StageState) Type() protoreflect.EnumType {
	return &file_toc_v1_toc_proto_enumTypes[0]
}

func (x StageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageState.Descriptor instead.
func (StageState) EnumDescriptor() ([]byte, []int) {
	return file_toc_v1_toc_proto_rawDescGZIP(), []int{0}
}

type ConstraintState int32

const (
	ConstraintState_CONSTRAINT_STATE_UNSPECIFIED   ConstraintState = 0
	ConstraintState_CONSTRAINT_STATE_UNKNOWN       ConstraintState = 1
	ConstraintState_CONSTRAINT_STATE_UNCONSTRAINED ConstraintState = 2
	ConstraintState_CONSTRAINT_STATE_AMBIGUOUS     ConstraintState = 3
	ConstraintState_CONSTRAINT_STATE_EMERGING      ConstraintState = 4
	ConstraintState_CONSTRAINT_STATE_IDENTIFIED    ConstraintState = 5
)

// Enum value maps for ConstraintState.
var (
	ConstraintState_name = map[int32]string{
		0: "CONSTRAINT_STATE_UNSPECIFIED",
		1: "CONSTRAINT_STATE_UNKNOWN",
		2: "CONSTRAINT_STATE_UNCONSTRAINED",
		3: "CONSTRAINT_STATE_AMBIGUOUS",
		4: "CONSTRAINT_STATE_EMERGING",
		5: "CONSTRAINT_STATE_IDENTIFIED",
	}
	ConstraintState_value = map[string]int32{
		"CONSTRAINT_STATE_UNSPECIFIED":   0,
		"CONSTRAINT_STATE_UNKNOWN":       1,
		"CONSTRAINT_STATE_UNCONSTRAINED": 2,
		"CONSTRAINT_STATE_AMBIGUOUS":     3,
		"CONSTRAINT_STATE_EMERGING":      4,
		"CONSTRAINT_STATE_IDENTIFIED":    5,
	}
)

func (x ConstraintState) Enum() *ConstraintState {
	p := new(ConstraintState)
	*p = x
	return p
}

func (x ConstraintState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstraintState) Descriptor() protoreflect.EnumDescriptor {
	return file_toc_v1_toc_proto_enumTypes[1].Descriptor()
}

func (ConstraintState) Type() protoreflect.EnumType {
	return &file_toc_v1_toc_proto_enumTypes[1]
}

func (x ConstraintState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstraintState.Descriptor instead.
func (ConstraintState) EnumDescriptor() ([]byte, []int) {
	return file_toc_v1_toc_proto_rawDescGZIP(), []int{1}
}

type ConstraintSource int32

const (
	ConstraintSource_CONSTRAINT_SOURCE_UNSPECIFIED     ConstraintSource = 0
	ConstraintSource_CONSTRAINT_SOURCE_INFERRED        ConstraintSource = 1
	ConstraintSource_CONSTRAINT_SOURCE_MANUAL_OVERRIDE ConstraintSource = 2
)

// Enum value maps for ConstraintSource.
var (
	ConstraintSource_name = map[int32]string{
		0: "CONSTRAINT_SOURCE_UNSPECIFIED",
		1: "CONSTRAINT_SOURCE_INFERRED",
		2: "CONSTRAINT_SOURCE_MANUAL_OVERRIDE",
	}
	ConstraintSource_value = map[string]int32{
		"CONSTRAINT_SOURCE_UNSPECIFIED":     0,
		"CONSTRAINT_SOURCE_INFERRED":        1,
		"CONSTRAINT_SOURCE_MANUAL_OVERRIDE": 2,
	}
)

func (x ConstraintSource) Enum() *ConstraintSource {
	p := new(ConstraintSource)
	*p = x
	return p
}

func (x ConstraintSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstraintSource) Descriptor() protoreflect.EnumDescriptor {
	return file_toc_v1_toc_proto_enumTypes[2].Descriptor()
}

func (ConstraintSource) Type() protoreflect.EnumType {
	return &file_toc_v1_toc_proto_enumTypes[2]
}

func (x ConstraintSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstraintSource.Descriptor instead.
func (ConstraintSource) EnumDescriptor() ([]byte, []int) {
	return file_toc_v1_toc_proto_rawDescGZIP(), []int{2}
}

// StageObservation is the canonical input to the analyzer.
// One per stage per analysis window.
//
// Invariant: busy_work + idle_work + blocked_work <= capacity_work.
// Failures is a subset of completions. Adapters should aim for
// equality in the work invariant; the analyzer tolerates inequality.
//
// Presence: idle_work, blocked_work, completions, failures, and
// queue_depth are optional — not all adapters can observe them.
// Non-optional scalars (busy_work, capacity_work, arrivals, workers)
// use proto3 default zero when absent. Converters validate semantics
// (e.g., stage name non-empty, counts non-negative).
type StageObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Stage string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	// Work accounting (abstract units — nanoseconds or ticks).
	BusyWork     uint64 `protobuf:"varint,2,opt,name=busy_work,json=busyWork,proto3" json:"busy_work,omitempty"`
	CapacityWork uint64 `protobuf:"varint,3,opt,name=capacity_work,json=capacityWork,proto3" json:"capacity_work,omitempty"`
	// Optional work accounting — absent means not observed.
	IdleWork    *uint64 `protobuf:"varint,4,opt,name=idle_work,json=idleWork,proto3,oneof" json:"idle_work,omitempty"`
	BlockedWork *uint64 `protobuf:"varint,5,opt,name=blocked_work,json=blockedWork,proto3,oneof" json:"blocked_work,omitempty"`
	// Item counters over the window.
	Arrivals    int64  `protobuf:"varint,6,opt,name=arrivals,proto3" json:"arrivals,omitempty"`
	Completions *int64 `protobuf:"varint,7,opt,name=completions,proto3,oneof" json:"completions,omitempty"`
	Failures    *int64 `protobuf:"varint,8,opt,name=failures,proto3,oneof" json:"failures,omitempty"`
	// Point-in-time gauges (end of window).
	QueueDepth    *int64 `protobuf:"varint,9,opt,name=queue_depth,json=queueDepth,proto3,oneof" json:"queue_depth,omitempty"`
	Workers       int32  `protobuf:"varint,10,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageObservation) Reset() {
	*x = StageObservation{}
	mi := &file_toc_v1_toc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageObservation) ProtoMessage() {}

func (x *StageObservation) ProtoReflect() protoreflect.Message {
	mi := &file_toc_v1_toc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageObservation.ProtoReflect.Descriptor instead.
func (*StageObservation) Descriptor() ([]byte, []int) {
	return file_toc_v1_toc_proto_rawDescGZIP(), []int{0}
}

func (x *StageObservation) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *StageObservation) GetBusyWork() uint64 {
	if x != nil {
		return x.BusyWork
	}
	return 0
}

func (x *StageObservation) GetCapacityWork() uint64 {
	if x != nil {
		return x.CapacityWork
	}
	return 0
}

func (x *StageObservation) GetIdleWork() uint64 {
	if x != nil && x.IdleWork != nil {
		return *x.IdleWork
	}
	return 0
}

func (x *StageObservation) GetBlockedWork() uint64 {
	if x != nil && x.BlockedWork != nil {
		return *x.BlockedWork
	}
	return 0
}

func (x *StageObservation) GetArrivals() int64 {
	if x != nil {
		return x.Arrivals
	}
	return 0
}

func (x *StageObservation) GetCompletions() int64 {
	if x != nil && x.Completions != nil {
		return *x.Completions
	}
	return 0
}

func (x *StageObservation) GetFailures() int64 {
	if x != nil && x.Failures != nil {
		return *x.Failures
	}
	return 0
}

func (x *StageObservation) GetQueueDepth() int64 {
	if x != nil && x.QueueDepth != nil {
		return *x.QueueDepth
	}
	return 0
}

func (x *StageObservation) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

// StageDiagnosis holds the classification for one stage.
// Contains ratios and counts, NOT rates. The caller converts to
// rates using their own time model (wall-clock or ticks).
type StageDiagnosis struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Stage       string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	State       StageState             `protobuf:"varint,2,opt,name=state,proto3,enum=toc.v1.StageState" json:"state,omitempty"`
	Utilization float64                `protobuf:"fixed64,3,opt,name=utilization,proto3" json:"utilization,omitempty"`
	// Optional ratios — absent when the source observation lacked
	// the corresponding work data.
	IdleRatio    *float64 `protobuf:"fixed64,4,opt,name=idle_ratio,json=idleRatio,proto3,oneof" json:"idle_ratio,omitempty"`
	BlockedRatio *float64 `protobuf:"fixed64,5,opt,name=blocked_ratio,json=blockedRatio,proto3,oneof" json:"blocked_ratio,omitempty"`
	ErrorRate    float64  `protobuf:"fixed64,6,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	QueueGrowth  int64    `protobuf:"varint,7,opt,name=queue_growth,json=queueGrowth,proto3" json:"queue_growth,omitempty"`
	// Passthrough counts for consumer rate computation.
	Completions   int64 `protobuf:"varint,8,opt,name=completions,proto3" json:"completions,omitempty"`
	Failures      int64 `protobuf:"varint,9,opt,name=failures,proto3" json:"failures,omitempty"`
	Arrivals      int64 `protobuf:"varint,10,opt,name=arrivals,proto3" json:"arrivals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageDiagnosis) Reset() {
	*x = StageDiagnosis{}
	mi := &file_toc_v1_toc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageDiagnosis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageDiagnosis) ProtoMessage() {}

func (x *StageDiagnosis) ProtoReflect() protoreflect.Message {
	mi := &file_toc_v1_toc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageDiagnosis.ProtoReflect.Descriptor instead.
func (*StageDiagnosis) Descriptor() ([]byte, []int) {
	return file_toc_v1_toc_proto_rawDescGZIP(), []int{1}
}

func (x *StageDiagnosis) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *StageDiagnosis) GetState() StageState {
	if x != nil {
		return x.State
	}
	return StageState_STAGE_STATE_UNSPECIFIED
}

func (x *StageDiagnosis) GetUtilization() float64 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *StageDiagnosis) GetIdleRatio() float64 {
	if x != nil && x.IdleRatio != nil {
		return *x.IdleRatio
	}
	return 0
}

func (x *StageDiagnosis) GetBlockedRatio() float64 {
	if x != nil && x.BlockedRatio != nil {
		return *x.BlockedRatio
	}
	return 0
}

func (x *StageDiagnosis) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *StageDiagnosis) GetQueueGrowth() int64 {
	if x != nil {
		return x.QueueGrowth
	}
	return 0
}

func (x *StageDiagnosis) GetCompletions() int64 {
	if x != nil {
		return x.Completions
	}
	return 0
}

func (x *StageDiagnosis) GetFailures() int64 {
	if x != nil {
		return x.Failures
	}
	return 0
}

func (x *StageDiagnosis) GetArrivals() int64 {
	if x != nil {
		return x.Arrivals
	}
	return 0
}

// Diagnosis is the output of one analyzer step.
type Diagnosis struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Constraint          string                 `protobuf:"bytes,1,opt,name=constraint,proto3" json:"constraint,omitempty"`
	SupportFreshness    float64                `protobuf:"fixed64,2,opt,name=support_freshness,json=supportFreshness,proto3" json:"support_freshness,omitempty"`
	Stages              []*StageDiagnosis      `protobuf:"bytes,3,rep,name=stages,proto3" json:"stages,omitempty"`
	StarvationCount     int64                  `protobuf:"varint,4,opt,name=starvation_count,json=starvationCount,proto3" json:"starvation_count,omitempty"`
	ConstraintState     ConstraintState        `protobuf:"varint,5,opt,name=constraint_state,json=constraintState,proto3,enum=toc.v1.ConstraintState" json:"constraint_state,omitempty"`
	ConstraintSource    ConstraintSource       `protobuf:"varint,6,opt,name=constraint_source,json=constraintSource,proto3,enum=toc.v1.ConstraintSource" json:"constraint_source,omitempty"`
	CandidateConstraint string                 `protobuf:"bytes,7,opt,name=candidate_constraint,json=candidateConstraint,proto3" json:"candidate_constraint,omitempty"`
	UnsupportedCount    int32                  `protobuf:"varint,8,opt,name=unsupported_count,json=unsupportedCount,proto3" json:"unsupported_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Diagnosis) Reset() {
	*x = Diagnosis{}
	mi := &file_toc_v1_toc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnosis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnosis) ProtoMessage() {}

func (x *Diagnosis) ProtoReflect() protoreflect.Message {
	mi := &file_toc_v1_toc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnosis.ProtoReflect.Descriptor instead.
func (*Diagnosis) Descriptor() ([]byte, []int) {
	return file_toc_v1_toc_proto_rawDescGZIP(), []int{2}
}

func (x *Diagnosis) GetConstraint() string {
	if x != nil {
		return x.Constraint
	}
	return ""
}

func (x *Diagnosis) GetSupportFreshness() float64 {
	if x != nil {
		return x.SupportFreshness
	}
	return 0
}

func (x *Diagnosis) GetStages() []*StageDiagnosis {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *Diagnosis) GetStarvationCount() int64 {
	if x != nil {
		return x.StarvationCount
	}
	return 0
}

func (x *Diagnosis) GetConstraintState() ConstraintState {
	if x != nil {
		return x.ConstraintState
	}
	return ConstraintState_CONSTRAINT_STATE_UNSPECIFIED
}

func (x *Diagnosis) GetConstraintSource() ConstraintSource {
	if x != nil {
		return x.ConstraintSource
	}
	return ConstraintSource_CONSTRAINT_SOURCE_UNSPECIFIED
}

func (x *Diagnosis) GetCandidateConstraint() string {
	if x != nil {
		return x.CandidateConstraint
	}
	return ""
}

func (x *Diagnosis) GetUnsupportedCount() int32 {
	if x != nil {
		return x.UnsupportedCount
	}
	return 0
}

// ObservationBatch wraps a set of observations for one analysis window.
// This is the wire message for NATS transport.
//
// All observations in a batch MUST refer to the same analysis window.
// The batch is produced by a single aggregator — there is no
// cross-host assembly. Stage names MUST be unique within a batch.
//
// timestamp_unix_nano is the window end time (when the aggregator
// sampled). window_duration_nano is the length of the analysis
// window. Together they define [end - duration, end).
type ObservationBatch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PipelineId         string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	TimestampUnixNano  int64                  `protobuf:"varint,2,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`    // window end, UTC nanoseconds
	WindowDurationNano int64                  `protobuf:"varint,3,opt,name=window_duration_nano,json=windowDurationNano,proto3" json:"window_duration_nano,omitempty"` // must be > 0
	Observations       []*StageObservation    `protobuf:"bytes,4,rep,name=observations,proto3" json:"observations,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ObservationBatch) Reset() {
	*x = ObservationBatch{}
	mi := &file_toc_v1_toc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationBatch) ProtoMessage() {}

func (x *ObservationBatch) ProtoReflect() protoreflect.Message {
	mi := &file_toc_v1_toc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationBatch.ProtoReflect.Descriptor instead.
func (*ObservationBatch) Descriptor() ([]byte, []int) {
	return file_toc_v1_toc_proto_rawDescGZIP(), []int{3}
}

func (x *ObservationBatch) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *ObservationBatch) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *ObservationBatch) GetWindowDurationNano() int64 {
	if x != nil {
		return x.WindowDurationNano
	}
	return 0
}

func (x *ObservationBatch) GetObservations() []*StageObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

var File_toc_v1_toc_proto protoreflect.FileDescriptor

const file_toc_v1_toc_proto_rawDesc = "" +
	"\n" +
	"\x10toc/v1/toc.proto\x12\x06toc.v1\"\xa4\x03\n" +
	"\x10StageObservation\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x1b\n" +
	"\tbusy_work\x18\x02 \x01(\x04R\bbusyWork\x12#\n" +
	"\rcapacity_work\x18\x03 \x01(\x04R\fcapacityWork\x12 \n" +
	"\tidle_work\x18\x04 \x01(\x04H\x00R\bidleWork\x88\x01\x01\x12&\n" +
	"\fblocked_work\x18\x05 \x01(\x04H\x01R\vblockedWork\x88\x01\x01\x12\x1a\n" +
	"\barrivals\x18\x06 \x01(\x03R\barrivals\x12%\n" +
	"\vcompletions\x18\a \x01(\x03H\x02R\vcompletions\x88\x01\x01\x12\x1f\n" +
	"\bfailures\x18\b \x01(\x03H\x03R\bfailures\x88\x01\x01\x12$\n" +
	"\vqueue_depth\x18\t \x01(\x03H\x04R\n" +
	"queueDepth\x88\x01\x01\x12\x18\n" +
	"\aworkers\x18\n" +
	" \x01(\x05R\aworkersB\f\n" +
	"\n" +
	"_idle_workB\x0f\n" +
	"\r_blocked_workB\x0e\n" +
	"\f_completionsB\v\n" +
	"\t_failuresB\x0e\n" +
	"\f_queue_depth\"\xfd\x02\n" +
	"\x0eStageDiagnosis\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12(\n" +
	"\x05state\x18\x02 \x01(\x0e2\x12.toc.v1.StageStateR\x05state\x12 \n" +
	"\vutilization\x18\x03 \x01(\x01R\vutilization\x12\"\n" +
	"\n" +
	"idle_ratio\x18\x04 \x01(\x01H\x00R\tidleRatio\x88\x01\x01\x12(\n" +
	"\rblocked_ratio\x18\x05 \x01(\x01H\x01R\fblockedRatio\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x06 \x01(\x01R\terrorRate\x12!\n" +
	"\fqueue_growth\x18\a \x01(\x03R\vqueueGrowth\x12 \n" +
	"\vcompletions\x18\b \x01(\x03R\vcompletions\x12\x1a\n" +
	"\bfailures\x18\t \x01(\x03R\bfailures\x12\x1a\n" +
	"\barrivals\x18\n" +
	" \x01(\x03R\barrivalsB\r\n" +
	"\v_idle_ratioB\x10\n" +
	"\x0e_blocked_ratio\"\x9e\x03\n" +
	"\tDiagnosis\x12\x1e\n" +
	"\n" +
	"constraint\x18\x01 \x01(\tR\n" +
	"constraint\x12+\n" +
	"\x11support_freshness\x18\x02 \x01(\x01R\x10supportFreshness\x12.\n" +
	"\x06stages\x18\x03 \x03(\v2\x16.toc.v1.StageDiagnosisR\x06stages\x12)\n" +
	"\x10starvation_count\x18\x04 \x01(\x03R\x0fstarvationCount\x12B\n" +
	"\x10constraint_state\x18\x05 \x01(\x0e2\x17.toc.v1.ConstraintStateR\x0fconstraintState\x12E\n" +
	"\x11constraint_source\x18\x06 \x01(\x0e2\x18.toc.v1.ConstraintSourceR\x10constraintSource\x121\n" +
	"\x14candidate_constraint\x18\a \x01(\tR\x13candidateConstraint\x12+\n" +
	"\x11unsupported_count\x18\b \x01(\x05R\x10unsupportedCount\"\xd3\x01\n" +
	"\x10ObservationBatch\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12.\n" +
	"\x13timestamp_unix_nano\x18\x02 \x01(\x03R\x11timestampUnixNano\x120\n" +
	"\x14window_duration_nano\x18\x03 \x01(\x03R\x12windowDurationNano\x12<\n" +
	"\fobservations\x18\x04 \x03(\v2\x18.toc.v1.StageObservationR\fobservations*\xa7\x01\n" +
	"\n" +
	"StageState\x12\x1b\n" +
	"\x17STAGE_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STAGE_STATE_HEALTHY\x10\x01\x12\x17\n" +
	"\x13STAGE_STATE_STARVED\x10\x02\x12\x17\n" +
	"\x13STAGE_STATE_BLOCKED\x10\x03\x12\x19\n" +
	"\x15STAGE_STATE_SATURATED\x10\x04\x12\x16\n" +
	"\x12STAGE_STATE_BROKEN\x10\x05*\xd5\x01\n" +
	"\x0fConstraintState\x12 \n" +
	"\x1cCONSTRAINT_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONSTRAINT_STATE_UNKNOWN\x10\x01\x12\"\n" +
	"\x1eCONSTRAINT_STATE_UNCONSTRAINED\x10\x02\x12\x1e\n" +
	"\x1aCONSTRAINT_STATE_AMBIGUOUS\x10\x03\x12\x1d\n" +
	"\x19CONSTRAINT_STATE_EMERGING\x10\x04\x12\x1f\n" +
	"\x1bCONSTRAINT_STATE_IDENTIFIED\x10\x05*|\n" +
	"\x10ConstraintSource\x12!\n" +
	"\x1dCONSTRAINT_SOURCE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONSTRAINT_SOURCE_INFERRED\x10\x01\x12%\n" +
	"!CONSTRAINT_SOURCE_MANUAL_OVERRIDE\x10\x02B$Z\"codeberg.org/binaryphile/toc/tocpbb\x06proto3"

var (
	file_toc_v1_toc_proto_rawDescOnce sync.Once
	file_toc_v1_toc_proto_rawDescData []byte
)

func file_toc_v1_toc_proto_rawDescGZIP() []byte {
	file_toc_v1_toc_proto_rawDescOnce.Do(func() {
		file_toc_v1_toc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_toc_v1_toc_proto_rawDesc), len(file_toc_v1_toc_proto_rawDesc)))
	})
	return file_toc_v1_toc_proto_rawDescData
}

var file_toc_v1_toc_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_toc_v1_toc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_toc_v1_toc_proto_goTypes = []any{
	(StageState)(0),          // 0: toc.v1.StageState
	(ConstraintState)(0),     // 1: toc.v1.ConstraintState
	(ConstraintSource)(0),    // 2: toc.v1.ConstraintSource
	(*StageObservation)(nil), // 3: toc.v1.StageObservation
	(*StageDiagnosis)(nil),   // 4: toc.v1.StageDiagnosis
	(*Diagnosis)(nil),        // 5: toc.v1.Diagnosis
	(*ObservationBatch)(nil), // 6: toc.v1.ObservationBatch
}
var file_toc_v1_toc_proto_depIdxs = []int32{
	0, // 0: toc.v1.StageDiagnosis.state:type_name -> toc.v1.StageState
	4, // 1: toc.v1.Diagnosis.stages:type_name -> toc.v1.StageDiagnosis
	1, // 2: toc.v1.Diagnosis.constraint_state:type_name -> toc.v1.ConstraintState
	2, // 3: toc.v1.Diagnosis.constraint_source:type_name -> toc.v1.ConstraintSource
	3, // 4: toc.v1.ObservationBatch.observations:type_name -> toc.v1.StageObservation
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_toc_v1_toc_proto_init() }
func file_toc_v1_toc_proto_init() {
	if File_toc_v1_toc_proto != nil {
		return
	}
	file_toc_v1_toc_proto_msgTypes[0].OneofWrappers = []any{}
	file_toc_v1_toc_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_toc_v1_toc_proto_rawDesc), len(file_toc_v1_toc_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toc_v1_toc_proto_goTypes,
		DependencyIndexes: file_toc_v1_toc_proto_depIdxs,
		EnumInfos:         file_toc_v1_toc_proto_enumTypes,
		MessageInfos:      file_toc_v1_toc_proto_msgTypes,
	}.Build()
	File_toc_v1_toc_proto = out.File
	file_toc_v1_toc_proto_goTypes = nil
	file_toc_v1_toc_proto_depIdxs = nil
}
